### PR TITLE
Fix zero time interval in example

### PR DESCRIPTION
**Pull request by boeddeker**

### CODE REVIEW

**Comment by thequilo** [comment]
This was intended as a corner case. Does it break something?

**Comment by boeddeker** [comment]
The visualisation is suboptimal for our toy example. It is difficult to see an utterance at 0. Was the corner case zero interval at zero or just zero interval?

**Comment by thequilo** [comment]
The corner case was just zero duration for any segment. You can also add an empty segment with zero duration

**Comment by boeddeker** [comment]
Ok, I moved the zero duration segment now to 1-1. There it is better recognizable. I also added an empty segment.

**Review by thequilo — APPROVED** [review]

**Pull request merged**
